language: python
python:
- '3.8'
- '3.9'
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run make test
deploy:
  provider: pypi
  username: "__token__"
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
  password:
    secure: oov+RjXd8o0RrPQDrl3BfKINKk5y2ttR7oJ/Zq2VAs5vqLpYyN473aqmWIn+i7OBLXpv1MEOGZJKC1CryutGjZEy0ZJlgHgweWJQu1AReDIE6bA3JD83MhLs/WRrsRnc20K3XXF56R7N0kv/l2Lya+JK5MURKGq5iezfKM+IeC2E/5dUoBq+tqv29uV7WbkZUNXO5iHHIIhqKt+Z+4XmrN2RUclSjA2TloavCGIXip6zzBZApuQAcU6EGwkXuEQTA9O7pgGx3b3LsXaD+VOD1mSNB7KhSEHcP7ZGkRHqZwRRtU3m+7yX6RCKtg+8S8MbF2Qy5ub7654btnNtHdRVL7d7Yxgg5ngCJu1OYTadaVI7pyz15d5LN5ASiqB78g0OOlzVpimOsoLd3C2fslLI2iGlG6F8Q0/AhnXp5MZMqdBp5CoQ0XJ5To7cvuOJAgDIm54XY0y6cvfF73EoicJCCzrqvQqN/mf2wS4wnnPYDAg1legCAws4Mcu6a/UuaY/6JIXTuT4Yw5AlfNRpL7RXidy/zjJ3GASlUia0jbAMEvY7RgLaF0zbkH5NL8qcpIaSsBWQ47N2U48pDU0qyvgVNIDM3BjtK6di3max5bWOtbagQezjurc1sS9eqkxubLMK5eBg8vM1UNM/r4pPifxiMwJ0lIsJs2yV9QlYrCMp6ww=
